instance:
  networking:
    ingress:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      security:
        forceHTTPS: false
        enableHSTS: false
      hosts:
        - host: openclaw.localhost
          paths:
            - path: /
              pathType: Prefix

  security:
    networkPolicy:
      allowedIngressNamespaces:
        - kube-system
