image:
  repository: ghcr.io/headlamp-k8s/headlamp
  tag: v0.40.1

replicaCount: 1

serviceAccount:
  name: headlamp-admin

rbac:
  clusterRole: view

service:
  type: ClusterIP
  port: 80
  targetPort: 4466

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: ""
  path: /
  pathType: Prefix
